repos:
  - repo: local
    hooks:
      - id: check-allowed-file-types
        name: Check that commited files has allowed type
        entry: Add file type if needed, but verify that formatter/linter are configured
        language: fail
        files: (?x)[/].*\.(?!(xml|tex|json|yaml|gitignore)$)[^.]+$
  - repo: https://github.com/spinergie/pre-commit-dprint
    rev: "v0.54.0"
    hooks:
      - id: dprint
        name: Formatting from dprint
  - repo: local
    hooks:
      - id: validate
        name: Validate Axiom's docbook
        entry: make -C Axioms_of_Liberalism validate
        language: system
        pass_filenames: false
        files: '\.xml$'
